name: github pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.100-preview.5.25277.114'

      - name: Install .NET WebAssembly Tools
        run: dotnet workload install wasm-tools

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: 'src/LlmTornado.Docs/website/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: src/LlmTornado.Docs/website

      - name: Build VitePress site
        run: npm run docs:build
        working-directory: src/LlmTornado.Docs/website

      - name: Add CNAME
        run: echo "llmtornado.ai" > src/LlmTornado.Docs/website/docs/.vitepress/dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/LlmTornado.Docs/website/docs/.vitepress/dist
          force_orphan: true